name: Auto-Clean

on:
<<<<<<< HEAD
  #自动清理：每周五早上2点自动清理
  schedule:
    - cron: 0 18 * * 4
=======
  #自动清理：每周早上3点
  schedule:
    - cron: 0 19 * * 0
>>>>>>> 8fcef6093b36a8b53aca8b090b016d01eb6e5bc5
  #手动清理
  workflow_dispatch:
    inputs:
      NUMBER:
        default: '0'
        required: false
        type: string

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions: write-all

jobs:
  auto_clean:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: ${{inputs.NUMBER || '0'}}
          delete_tags: true

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1
