#CI项目
name: CWRT-ALL

#CI计划
on:
  #自动编译：周五早上4点
  #github使用UTC时区 北京时间比Github所使用时区快8个小时
  #每周五早上8点开始编译
  # schedule:
  #   - cron: 0 20 * * 4
  #手动编译
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，仅限一个。'
        required: false
        type: string
      ADJUST:
        description: '内存低占用模式，默认关闭。'
        default: 'false'
        required: false
        type: boolean
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean

#CI权限
permissions: write-all

#CI任务
jobs:
  wrt_config:
    name: ${{matrix.TARGET}}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        TARGET: [MTK-7981, MTK-7986]
        SOURCE: [hanwckf/immortalwrt-mt798x, padavanonly/immortalwrt-mt798x, Aabandon/immortalwrt-mt798x]
        BRANCH: [openwrt-21.02]
        include:
          - SOURCE: Aabandon/immortalwrt-mt798x
            BRANCH: test

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译平台
      WRT_TARGET: ${{matrix.TARGET}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: CWRT
      #默认WIFI名
      WRT_WIFI: CWRT
      #默认地址
      WRT_IP: 192.168.10.1
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #默认源码
      WRT_URL: https://github.com/${{matrix.SOURCE}}.git
      #默认分支
      WRT_BRANCH: ${{matrix.BRANCH}}
      #插件调整
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      #内存低占用模式
      WRT_ADJUST: ${{inputs.ADJUST}}
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}
